<?php
namespace langs\langssystem;

use Illuminate\Database\Seeder;

class LangFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lang_fields')->delete();
        
        \DB::table('lang_fields')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_lang' => 1,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'ZAPATO CASUAL',
                'description' => 'CategoryDescription-es',
                'uri' => 'zapato-casualcategory',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'id_lang' => 2,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'SHOES-casualcategory',
                'description' => 'CategorytDescription-en  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis, aperiam, animi. Id quam magni itaque quos mollitia facere fugiat accusamus tempora molestias laudantium, sed nostrum dicta voluptas nihil libero deleniti.',
                'uri' => 'wedding-casualcategory',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'id_lang' => 3,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'chaussure casual',
                'description' => 'chaussure-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima ducimus consequatur necessitatibus deserunt aut repellendus minus, autem expedita temporibus asperiores ipsum enim, distinctio excepturi aliquam perferendis velit magni voluptatem, consectetur!',
                'uri' => 'chaussure-casualcategory',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'id_lang' => 1,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'zapato bodas',
                'description' => 'CategoryDescription-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit nisi sit delectus alias fugiat minima placeat fuga, atque, necessitatibus provident quasi commodi, vel soluta libero dolorem enim dolor accusamus blanditiis?',
                'uri' => 'zapato-bodas',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'id_lang' => 2,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'wedding shoe',
                'description' => 'CategorytDescription-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus nam deleniti impedit a dolorem dolorum, facere veniam libero magnam dolor et iure ratione. Necessitatibus assumenda dolores facere, ipsam quia, veritatis?',
                'uri' => 'wedding-shoe-category',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'id_lang' => 3,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'chaussure catégorie',
                'description' => 'CategoryDescription-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus recusandae pariatur sint inventore quasi, perspiciatis aspernatur blanditiis voluptatibus, quis ipsam ratione fugit. Veniam tempore sit harum, quo eligendi, incidunt perspiciatis.',
                'uri' => 'chaussure-bodas-categorie',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'id_lang' => 1,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'fiestas-zapatos-es',
                'description' => 'CategoryDescription-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, voluptatem facere eaque maiores voluptatibus aspernatur nihil dolores doloribus magnam molestias, possimus eveniet ullam enim expedita inventore magni officiis aliquam ex!',
                'uri' => 'fiestas-zapatos-es',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'id_lang' => 2,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'party-shoes',
                'description' => 'CategorytDescription-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore est dignissimos reprehenderit laudantium nihil, autem a aspernatur laboriosam numquam voluptates reiciendis soluta, quo praesentium temporibus nobis placeat corporis rem unde?',
                'uri' => 'party-shoes',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'id_lang' => 3,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'zapato-fiestas-fr',
                'description' => 'CategoryDescription-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam voluptatibus facilis quod maxime, sequi nulla ducimus vitae tempore quia nobis numquam, dolor at quo cumque, iure assumenda, accusamus temporibus autem?',
                'uri' => 'zapato-fiestas-fr',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'id_lang' => 1,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'urbanos',
                'description' => 'CategoryDescription-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, error nesciunt cupiditate nam libero soluta illo consequatur cum asperiores, odit repellendus tenetur quisquam eius eum perspiciatis optio quia culpa numquam?',
                'uri' => 'urbanos',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'id_lang' => 2,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'urbans',
                'description' => 'CategorytDescription-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam doloremque fugit, dignissimos totam commodi odit, obcaecati cupiditate ducimus ullam, reiciendis odio repellat excepturi iusto. Saepe officiis quisquam, quis sit recusandae!',
                'uri' => 'urbans',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'id_lang' => 3,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Category',
                'name' => 'urbane',
                'description' => 'CategoryDescription-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis voluptatum consequuntur a molestiae, dolore nesciunt sed sapiente totam eaque. Repudiandae, ab, doloremque! Dolorum sapiente dolorem harum debitis! Assumenda, fuga, cum!',
                'uri' => 'urbane',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'id_lang' => 1,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'ZAPATO DE TACON',
                'description' => '<p>zapato tacon-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro debitis magni aspernatur molestiae illo eius eaque tempora hic excepturi, asperiores cumque magnam, beatae quod. Atque quaerat explicabo, nihil repudiandae vero fugiat, sequi minima illo corporis tempore! Sapiente voluptatem, ab et iusto. Non similique minima in veritatis iusto reprehenderit enim commodi magni molestias officiis quisquam pariatur ea, error soluta iste ratione eaque odit eveniet atque. Dicta totam quibusdam distinctio deserunt fuga in, velit debitis quas tempora error quod aut quia accusantium ab rem id, rerum commodi veritatis ex eligendi. Dignissimos reprehenderit, sunt doloremque repellat cum debitis. Sunt consectetur repellendus dolor architecto?</p>',
                'uri' => 'tacon-productes',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:34:01',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'id_lang' => 2,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'TACON SHOE',
                'description' => '<p>zapato tacon-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit facilis odio autem, rem placeat totam, voluptates nostrum magnam fugiat nemo, accusamus nulla soluta veniam impedit perferendis. Tempore, tenetur, facere. Expedita odio deserunt odit. Iste velit cupiditate omnis sequi repellat rerum corporis ea molestiae accusantium numquam eligendi cum, quaerat aliquid, adipisci ipsa, tenetur hic? Odit officia, iusto fuga iste odio eos, praesentium, debitis optio harum voluptatibus inventore! Quia esse, dolorem, necessitatibus beatae praesentium odit architecto dolor eaque, quisquam commodi sed. Beatae veniam placeat adipisci illo quasi ex facilis, voluptatibus in. Eveniet sequi quae labore. Quaerat tenetur iusto, omnis ratione dicta earum!</p>',
                'uri' => 'zapato-tacon-en',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:34:01',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'id_lang' => 3,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato tacon-fr',
                'description' => '<p>zapato tacon-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut reprehenderit quis, quidem, eaque temporibus nam nostrum voluptate, atque officia labore id veniam explicabo eius quos accusamus maxime vitae vel, dolorem nihil sit cumque cum? A ea facilis odit eius inventore debitis quaerat quae, provident minima amet dicta laboriosam consequatur, tempore quo suscipit aspernatur. Distinctio, alias! Hic id quisquam, illum corrupti nobis perferendis quos magni eum fuga. Hic id vero fugit quam ipsam saepe, quis recusandae dolorem quasi voluptate earum neque amet illo accusantium ad sed, cumque. Laudantium, qui? Voluptas illo, culpa ex nulla explicabo magni! Adipisci consequatur laborum, voluptates minima!</p>',
                'uri' => 'zapato-tacon-fr',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:34:01',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'id_lang' => 1,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato-fiesta-es',
                'description' => '<p>zapato fiesta-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam sunt, voluptatem tempora delectus accusamus inventore, quasi distinctio nostrum at rem quos modi adipisci odit incidunt aliquid illo? Soluta ipsam consectetur asperiores libero maiores ex impedit suscipit, distinctio, consequatur fugiat ea, deleniti facere obcaecati maxime ut alias accusamus officia. Delectus laborum quaerat, excepturi reprehenderit voluptatibus. Dolore ipsam reprehenderit fuga fugit molestias, est necessitatibus minus, suscipit saepe itaque cum amet soluta neque earum laudantium, placeat facilis sunt ullam tempora. Quasi et facere dignissimos impedit nobis eos accusantium porro odio autem maxime ut, necessitatibus placeat deserunt accusamus possimus ullam sapiente inventore magni assumenda.</p>',
                'uri' => 'zapato-fiesta-es',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:30:30',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'id_lang' => 2,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato-fiesta-en',
                'description' => '<p>zapato fiesta-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur accusantium incidunt neque, nisi itaque. Eius fugiat quibusdam eos dolore vitae, accusantium natus, voluptatem, aliquam, temporibus perspiciatis quod dolorum officiis? Harum fuga ut, voluptate delectus nihil dolor, quidem! Dolorum iusto, at iure recusandae doloribus corporis odio quo architecto autem repellendus dicta obcaecati, dolores veritatis expedita accusantium tenetur similique nulla consequatur. Sint adipisci ab, autem modi, eum accusamus odit. Repellat voluptatem asperiores officiis dolores adipisci, soluta nihil, magnam quis modi rem, sunt. Praesentium, sunt fugit. Natus nulla voluptates omnis officiis ab molestiae commodi laborum veritatis. Quis quae, saepe, et obcaecati eveniet molestiae.</p>',
                'uri' => 'zapato-fiesta-en',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:30:30',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'id_lang' => 3,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato fiesta-fr',
                'description' => '<p>zapato fiesta-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima distinctio quae debitis quo fugit beatae. Animi quisquam est excepturi eaque. In, nostrum laudantium, ducimus molestiae illo iure quibusdam tempora voluptatem autem quis eaque minus provident eum maiores. Voluptas cumque, autem labore rerum non veniam iste quae numquam quibusdam tempore, molestias vitae repellendus quisquam fuga similique. Voluptates incidunt veniam deserunt est officiis aperiam quas maiores, voluptas quod fugiat laudantium alias quis consectetur eaque provident harum facilis nulla reiciendis temporibus hic, placeat tempora fuga quo esse. Voluptatum illo laudantium necessitatibus autem expedita corporis officiis, unde quasi omnis quod repellendus fuga corrupti deleniti!</p>',
                'uri' => 'zapato-fiesta-fr',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:30:30',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'id_lang' => 1,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato-plano',
                'description' => '<p>zapato plano-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est sapiente odio, doloremque numquam facilis animi magnam debitis dicta nihil iure. Veritatis ut et expedita totam deleniti, animi vel est, beatae reiciendis dolor pariatur, aut mollitia ex quam dignissimos consectetur assumenda quod architecto minima facere praesentium minus. At voluptatum fugit doloribus velit natus incidunt repellendus vel veniam laborum officia aperiam dicta obcaecati tenetur, dolores molestiae animi suscipit nam ipsam, vero vitae. Ut distinctio eaque optio blanditiis nihil deserunt sunt, inventore fuga praesentium nulla at, officiis laborum laboriosam eveniet dolore earum iste, veritatis sit explicabo aperiam. Ex reiciendis eum, nobis aspernatur saepe.</p>',
                'uri' => 'zapato-plano',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:55:47',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'id_lang' => 2,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'plain-shoe',
                'description' => '<p>zapato plano-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, suscipit ipsa, alias vel et architecto explicabo dicta voluptas repudiandae consequatur aliquam sunt fugiat, ducimus, excepturi dolor maxime assumenda incidunt. Maxime dolorum fugiat perspiciatis expedita, recusandae perferendis repellat, suscipit saepe? Aliquid vitae ipsa aliquam nisi. Quo repudiandae aperiam ratione ad accusamus architecto nihil. Rerum minima fugiat voluptates architecto minus dignissimos quaerat soluta quas. Modi, suscipit obcaecati quidem. Dignissimos, consequatur, delectus. Incidunt ipsum cupiditate quidem mollitia. Minima est amet laudantium a deserunt et, iusto labore numquam. Vitae rem deleniti tempore. Nesciunt quo temporibus ad nemo earum veniam soluta inventore tempore placeat ducimus.</p>',
                'uri' => 'plain-shoe',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:55:47',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'id_lang' => 3,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'trousse',
                'description' => '<p>zapato plano-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi voluptates nisi provident porro dolor eos quibusdam ipsam nam doloribus, mollitia officia, dolorum voluptas repellendus obcaecati magni alias, at omnis praesentium sed voluptate ipsa dolore nulla hic! At sit inventore magni dolorem nihil eius facere eos veritatis iure velit dolorum reprehenderit minus, ea nostrum unde cupiditate excepturi doloremque voluptatum, laborum distinctio harum. Nesciunt amet, velit ut laborum! Ex, ut, nobis. Ipsam maxime accusamus iure, voluptate, recusandae quibusdam dolore consectetur veniam. Ducimus aliquam tempora, labore nobis obcaecati in quos saepe quibusdam illo impedit animi! Eaque neque earum libero, quam eligendi molestias debitis.</p>',
                'uri' => 'trousse',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:55:47',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'id_lang' => 1,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'botin-es',
                'description' => '<p>botin-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus totam, nulla, vero consectetur vitae pariatur corporis debitis, rem animi cumque et sed ad at commodi, hic iusto? Quisquam delectus saepe voluptatum voluptates! Quia odit, quod alias reiciendis illo molestiae suscipit aut, nulla iste doloremque libero labore dolorum consequuntur veniam dolore ipsam dolor. Facere, sint, perferendis sapiente maiores distinctio saepe error maxime labore, blanditiis incidunt excepturi ab, odio beatae quia? Dolore illo hic, aut? Fugit incidunt aliquid nobis ea tempore non beatae tenetur a, adipisci sit. Beatae sint, quo, qui possimus recusandae consequatur, ad, vel magni excepturi nisi ducimus fugit eum.</p>',
                'uri' => 'botin-es',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:31:03',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'id_lang' => 2,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'botin-en',
                'description' => '<p>botin-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem eaque tempore sapiente veniam vel velit quas minima quidem suscipit quisquam. Cumque doloribus animi pariatur modi quaerat veritatis fugiat aspernatur voluptate tempora autem quia, velit corporis earum placeat accusantium eveniet! Quasi suscipit incidunt ipsam autem eius eum illo aliquid qui vel mollitia quibusdam, et iure, cumque omnis nihil! Est cumque reprehenderit cupiditate nam aut, at, rerum ab blanditiis magnam cum, et! Ad illum aspernatur nostrum repellendus enim blanditiis libero est! Accusantium ad eaque officiis sunt voluptatibus, id porro quod ut officia magni repellat consectetur nisi recusandae modi totam, commodi nam fugiat.</p>',
                'uri' => 'botin-en',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:31:03',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'id_lang' => 3,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'lebotin',
                'description' => '<p>botin-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum neque repellendus dignissimos quia dolores eos ab eius cum numquam consequuntur esse molestiae magni impedit voluptates ut dicta velit, nisi quod, omnis consequatur fuga! Minus vel praesentium, laudantium eius voluptatibus consequatur dolores quisquam dignissimos, magni animi, debitis! Quas reiciendis, repudiandae facilis officiis aut incidunt aliquid dolorem perspiciatis veritatis a aspernatur! Quia labore beatae ducimus nihil optio voluptas tempora minus explicabo. Alias eligendi voluptatibus possimus mollitia omnis ut autem beatae incidunt, odit voluptatum laudantium quasi et aliquam illum, voluptatem ducimus consequuntur fuga, veniam nemo. Libero, fugiat. Asperiores explicabo earum dolorum, magnam beatae.</p>',
                'uri' => 'lebotin',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:31:03',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'id_lang' => 1,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'zapato de verano',
                'description' => '<p>zapato veraniego-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur non illo et nostrum libero maxime est maiores ipsum animi consequuntur itaque ullam, autem rem vero nihil adipisci corporis praesentium molestias quas quia id in. Nobis, atque optio libero enim hic expedita modi, alias, ex repudiandae vel esse mollitia. Saepe beatae quisquam aperiam nihil velit ducimus cum corporis sequi deleniti dignissimos distinctio cupiditate earum reprehenderit minima facilis mollitia qui in ipsum numquam, voluptates dolore modi. Ad hic fuga officia, fugit molestiae aspernatur aliquam amet beatae officiis animi obcaecati quia quae omnis praesentium in atque excepturi. Quasi quaerat blanditiis perferendis ab deserunt.</p>',
                'uri' => 'zapato-de-verano',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:45:40',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'id_lang' => 2,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'shoe primaveral',
                'description' => '<p>zapato veraniego-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita consequuntur odio cumque culpa? Esse, sed laborum voluptate temporibus deserunt. Mollitia possimus deserunt delectus nostrum minus dolor eaque nemo adipisci molestiae eum, repellendus qui iste necessitatibus explicabo cum architecto aspernatur veritatis soluta culpa quam, beatae vitae est praesentium autem sit. Voluptates dolorem totam consequuntur quos? Recusandae odit, beatae, minima, molestiae accusamus explicabo officiis vel placeat dolor velit, sapiente pariatur eligendi amet omnis quam quos adipisci commodi illo? Cupiditate magnam earum ipsum provident repudiandae deserunt, voluptatem quae aliquid? Magnam expedita sunt tempore, asperiores voluptas, perspiciatis quo labore facilis? Sit quae, pariatur possimus?</p>',
                'uri' => 'primaveral-shoe',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:45:40',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'id_lang' => 3,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'chaussure de printemps',
                'description' => '<p>zapato veraniego-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, nam nisi porro praesentium, adipisci, illum totam eligendi voluptate sapiente iure quibusdam tenetur eum animi? Natus sint quae autem velit, sit id. Tenetur ducimus ea accusantium. Iusto excepturi impedit necessitatibus vitae nisi quas nobis corporis architecto similique, et quam illo enim nam illum sunt. Magnam veritatis veniam voluptatem, ab velit temporibus officiis porro sapiente qui maxime, ut aspernatur recusandae quae, quia et sit voluptate autem corrupti rem nostrum voluptatum blanditiis ipsam reiciendis dolor. Maxime odio quos ducimus blanditiis, laborum expedita. Explicabo ipsam error nulla, voluptate fugit repellat possimus cumque dolorem magni.</p>',
                'uri' => 'chaussure-de-printemps',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-05 04:45:40',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'id_lang' => 1,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'ZAPATO FINO',
                'description' => '<p>zapato-fino-es Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, quibusdam laudantium provident eligendi delectus nemo. Sed laborum eligendi sequi omnis ullam officiis at modi autem consequatur saepe tenetur maiores velit dolorem pariatur deserunt labore totam, cumque eius! Labore ratione doloribus ad non, quidem blanditiis reiciendis animi nesciunt perspiciatis, iste. Ab quia nobis, praesentium ad beatae ullam omnis esse consequuntur velit porro sed reiciendis corporis alias explicabo autem cumque cupiditate eum, quisquam neque, itaque. Hic unde earum sit debitis cum iure numquam, fuga odio tempore, sint, a ipsum ex tempora voluptatem harum dolor, magni explicabo inventore doloremque laudantium ipsam eaque possimus?</p>',
                'uri' => 'zapato-fino',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:37:20',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'id_lang' => 2,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'FINE SHOE',
                'description' => '<p>zapato-fino-en Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis eaque porro a alias numquam ab non odit omnis sit. Optio, officiis, enim! Eius eos, sint consequatur, assumenda hic quia repudiandae perspiciatis voluptatum, ullam temporibus tempore eligendi commodi placeat quae itaque sequi accusamus ab nihil adipisci. Tempore aliquid illum provident, ullam! Corrupti qui aperiam mollitia ad quis error doloremque. Delectus autem, architecto mollitia nesciunt cumque quod at perferendis, laborum odit eligendi, facere doloremque. Explicabo esse saepe, vel autem commodi, consequatur voluptates debitis earum nihil, non necessitatibus accusantium in asperiores. Accusamus qui, eligendi. Rem sapiente itaque est cumque distinctio beatae, consectetur velit.</p>',
                'uri' => 'fine-shoe',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:37:20',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'id_lang' => 3,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Product',
                'name' => 'chaussure fine',
                'description' => '<p>zapato-fino-fr Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus hic quaerat distinctio, aut qui consequuntur facilis quibusdam fuga dolorem, tenetur nesciunt excepturi odio corrupti voluptatem fugit pariatur repellendus deleniti maiores cupiditate magni reprehenderit delectus? Excepturi voluptatum saepe animi expedita libero itaque neque corporis quibusdam cumque vel et possimus delectus magnam dolorum rerum illo nulla, eius, enim labore aliquam? Nulla libero recusandae placeat nisi soluta amet, debitis. Quaerat neque, quidem pariatur, accusamus enim nobis saepe sunt rem quibusdam voluptas tempora totam tempore eos sint libero repellat porro eius harum unde dicta vero quis fugiat. Minus impedit asperiores iste ipsam recusandae praesentium?</p>',
                'uri' => 'chaussure-fine',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => '2017-12-04 07:37:20',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 34,
                'id_lang' => 1,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'Colores',
                'description' => 'Color-es',
                'uri' => 'Colores',
                'features' => 'nomatterbythemoment',                                    
                'html_block' => NULL,
                'otherfields' => 'nomatterbythemoment',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'id_lang' => 2,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'Color',
                'description' => 'Color-en',
                'uri' => 'Color',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 36,
                'id_lang' => 3,
                'langstable_id' => 1,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'Colour',
                'description' => 'Color-fr',
                'uri' => 'Colour',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 37,
                'id_lang' => 1,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'talla',
                'description' => 'talla-es',
                'uri' => 'talla',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 38,
                'id_lang' => 2,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'size',
                'description' => 'size-en',
                'uri' => 'size',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 39,
                'id_lang' => 3,
                'langstable_id' => 2,
                'langstable_type' => 'App\\Models\\Attribute',
                'name' => 'taille',
                'description' => 'taille-fr',
                'uri' => 'taille',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'id_lang' => 1,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '38',
                'description' => '<p>Default-es</p>',
                'uri' => 'S-talla',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:18',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'id_lang' => 2,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '38',
                'description' => '<p>Default-en</p>',
                'uri' => 'S-size',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:18',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'id_lang' => 3,
                'langstable_id' => 3,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '38',
                'description' => '<p>Default-fr</p>',
                'uri' => 'S-taille',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:18',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
                'id_lang' => 1,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '36',
                'description' => '<p>Default-es</p>',
                'uri' => 'M-talla',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:25',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'id_lang' => 2,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '36',
                'description' => '<p>Default-en</p>',
                'uri' => 'M-size',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:25',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 51,
                'id_lang' => 3,
                'langstable_id' => 4,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '36',
                'description' => '<p>Default-fr</p>',
                'uri' => 'M-taille',
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-28 05:09:25',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 52,
                'id_lang' => 1,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '40',
                'description' => '<p>40</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:09:47',
                'updated_at' => '2017-11-28 05:09:47',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 53,
                'id_lang' => 2,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '40',
                'description' => '<p>40</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:09:47',
                'updated_at' => '2017-11-28 05:09:47',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 54,
                'id_lang' => 3,
                'langstable_id' => 5,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '40',
                'description' => '<p>40</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:09:47',
                'updated_at' => '2017-11-28 05:09:47',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 55,
                'id_lang' => 1,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '42',
                'description' => '<p>42</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:11:26',
                'updated_at' => '2017-11-28 05:11:26',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 56,
                'id_lang' => 2,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '42',
                'description' => '<p>42</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:11:26',
                'updated_at' => '2017-11-28 05:11:26',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 57,
                'id_lang' => 3,
                'langstable_id' => 6,
                'langstable_type' => 'App\\Models\\Option',
                'name' => '42',
                'description' => '<p>42</p>',
                'uri' => NULL,
                'features' => NULL,                                    
                'html_block' => NULL,
                'otherfields' => NULL,
                'created_at' => '2017-11-28 05:11:26',
                'updated_at' => '2017-11-28 05:11:26',
                'deleted_at' => NULL,
            ),
 
        ));
        
        
    }
}